

export const ADD_TO_CART="ADD_TO_CART"
export const REMOVE_TO_CART="REMOVE_TO_CART"


export const GET_CATEGORY_SUCCESS="GET_CATEGORY_SUCCESS"
export const CHANGE_CATEGORY="CHANGE_CATEGORY"
export const ZERO_CATEGORY="ZERO_CATEGORY"


export const GET_BEST_PRODUCT_SUCCESS="GET_BEST_PRODUCT_SUCCESS"
export const GET_PRODUCTS_SUCCESS="GET_PRODUCTS_SUCCESS"