

export const ADD_TO_CART="ADD_TO_CART"
export const REMOVE_TO_CART="REMOVE_TO_CART"
export const INCREMENT_QUANTİTY="INCREMENT_QUANTİTY"
export const DECREMENT_QUANTİTY="DECREMENT_QUANTİTY"


export const GET_CATEGORY_SUCCESS="GET_CATEGORY_SUCCESS"
 

export const GET_PRODUCTS_UNITPRICE_SUCCESS="GET_PRODUCTS_UNITPRICE_SUCCESS"
export const GET_ORDER_PRODUCTS_SUCCESS="GET_ORDER_PRODUCTS_SUCCESS"
export const GET_SEARCH_PRODUCTS="GET_SEARCH_PRODUCTS"
export const GET_BEST_PRODUCT_SUCCESS="GET_BEST_PRODUCT_SUCCESS"
export const GET_PRODUCTS_SUCCESS="GET_PRODUCTS_SUCCESS"