

export const ADD_TO_CART="ADD_TO_CART"
export const REMOVE_TO_CART="REMOVE_TO_CART"
export const INCREMENT_QUANTİTY="INCREMENT_QUANTİTY"
export const DECREMENT_QUANTİTY="DECREMENT_QUANTİTY"


export const GET_CATEGORY_SUCCESS="GET_CATEGORY_SUCCESS"
 

export const GET_PRODUCTS_UNITPRICE_SUCCESS="GET_PRODUCTS_UNITPRICE_SUCCESS"
export const GET_ORDER_PRODUCTS_SUCCESS="GET_ORDER_PRODUCTS_SUCCESS"
export const GET_SEARCH_PRODUCTS="GET_SEARCH_PRODUCTS"
export const GET_BEST_PRODUCT_SUCCESS="GET_BEST_PRODUCT_SUCCESS"
export const GET_PRODUCTS_SUCCESS="GET_PRODUCTS_SUCCESS"


export const LOGIN_USER_SUCCESS="LOGIN_USER_SUCCESS"
export const IS_LOGIN_USER="IS_LOGIN_USER"
export const GET_USER_BY_ID_SUCCESS="GET_USER_BY_ID_SUCCESS"
export const UPDATE_USER_BY_ID_SUCCESS="UPDATE_USER_BY_ID_SUCCESS"
export const UPDATE_USER_BY_ID_ERROR="UPDATE_USER_BY_ID_ERROR"


export const GET_COMMENTS_BY_USER_ID_SUCCESS="GET_COMMENTS_BY_USER_ID_SUCCESS"

export const CREATE_ORDER="CREATE_ORDER"